set shell := ["bash", "-ceu"]

# Runs the passing deterministic gate for an incremental main change. Requires just 1.58.0.
check:
    go run ./cmd/generate-requirement-manifest --check
    go run ./cmd/afk-evidence -mode validate -file evidence/afk/m0-foundation-local.json
    go mod verify
    go test -race ./...
    go vet ./...
    go run ./cmd/no-real-wait --root .
    go run ./cmd/ledger-report --catalog evidence/requirements-catalog.json --ledger evidence/requirements-ledger.json

# Runs check, then requires all 183 rows to have valid completed evidence.
verify: check
    go run ./cmd/ledger-report --catalog evidence/requirements-catalog.json --ledger evidence/requirements-ledger.json --complete

# Compatibility alias for the final completion gate.
completion-check: verify

# Installs the locked public-docs toolchain and starts the local Docusaurus site.
docs:
    npm --prefix website ci
    npm --prefix website run start

# Regenerates allow-listed documentation, validates it, and prints its exact diff.
docs-generate:
    go run ./skills/refresh-agent-runtime-docs/scripts/refresh-docs --root .

# Proves generated bytes, TypeScript, links, routes, and the production site build.
docs-check:
    go run ./skills/refresh-agent-runtime-docs/scripts/refresh-docs --root . --check
    npm --prefix website ci
    npm --prefix website audit --omit=dev --audit-level=high
    npm --prefix website run typecheck
    npm --prefix website run build
