set shell := ["bash", "-ceu"]

# Runs the passing deterministic gate for an incremental main change. Requires just 1.58.0.
check:
    go run ./cmd/generate-requirement-manifest --check
    go run ./cmd/generate-runtime-openapi --check
    for evidence_file in evidence/afk/*.json; do go run ./cmd/afk-evidence -mode validate -file "$evidence_file"; done
    go mod verify
    go test -race ./...
    go vet ./...
    go run ./cmd/no-real-wait --root .
    go run ./cmd/ledger-report --catalog evidence/requirements-catalog.json --ledger evidence/requirements-ledger.json

# Regenerates checked-in source artifacts from their binding authorities.
generate:
    go run ./cmd/generate-requirement-manifest
    go run ./cmd/generate-runtime-openapi

# Runs check, then requires all 183 rows to have valid completed evidence.
verify: check
    go run ./cmd/ledger-report --catalog evidence/requirements-catalog.json --ledger evidence/requirements-ledger.json --complete

# Compatibility alias for the final completion gate.
completion-check: verify

# Requires the protected self-hosted Linux/x86_64/KVM runner contract and always
# retains a redacted blocked report rather than treating a local machine as proof.
firecracker-smoke report="evidence/firecracker-smoke.json" vm_id="" uid="0" gid="0" cgroup_parent="" stack_resource="" external_owner="" fixture_lock="tools/firecracker/fixtures.lock":
    go run ./cmd/firecracker-smoke -report "{{ report }}" -fixture-lock "{{ fixture_lock }}" -vm-id "{{ vm_id }}" -uid "{{ uid }}" -gid "{{ gid }}" -cgroup-parent "{{ cgroup_parent }}" -stack-resource "{{ stack_resource }}" -external-owner "{{ external_owner }}"

# Compatibility alias for the protected boot harness. It is not the enrolled
# public runtime-command integration suite.
firecracker-integration report="evidence/firecracker-integration.json" vm_id="" uid="0" gid="0" cgroup_parent="" stack_resource="" external_owner="" fixture_lock="tools/firecracker/fixtures.lock":
    just firecracker-smoke "{{ report }}" "{{ vm_id }}" "{{ uid }}" "{{ gid }}" "{{ cgroup_parent }}" "{{ stack_resource }}" "{{ external_owner }}" "{{ fixture_lock }}"

# Installs the locked Astro Starlight toolchain and starts the local site.
docs:
    npm --prefix website ci
    npm --prefix website run start

# Regenerates allow-listed documentation, validates it, and prints its exact diff.
docs-generate:
    go run ./skills/refresh-agent-runtime-docs/scripts/refresh-docs --root .

# Proves generated bytes, TypeScript, links, routes, and the production site build.
docs-check:
    go run ./skills/refresh-agent-runtime-docs/scripts/refresh-docs --root . --check
    npm --prefix website ci
    npm --prefix website audit --omit=dev --audit-level=high
    npm --prefix website run typecheck
    npm --prefix website run build
    npm --prefix website run check:routes

# Starts one isolated declarative OrbStack environment. STACK is optional; an
# omitted value derives a deterministic identity from this worktree.
dev stack="":
    go run ./tools/dev up --stack "{{stack}}" --root .

dev-preflight stack="":
    go run ./tools/dev preflight --stack "{{stack}}" --root .

dev-status stack="":
    go run ./tools/dev status --stack "{{stack}}" --root .

# Opens a foreground OS-selected API forward. Ctrl-C closes only the forward.
dev-api stack="":
    go run ./tools/dev api --stack "{{stack}}" --root .

# Restarts all eight declared local runtime-role Deployments after label/UID checks.
dev-reset stack="":
    go run ./tools/dev reset --stack "{{stack}}" --root .

# Deletes only a verified labelled Stack namespace and its declared local objects.
dev-down stack="":
    go run ./tools/dev down --stack "{{stack}}" --root .

# Proves two full Stack instances coexist and teardown remains contained.
two-stack-smoke profile="local" context="orbstack" evidence="":
    AGENT_RUNTIME_DEV_PROFILE="{{profile}}" AGENT_RUNTIME_DEV_CONTEXT="{{context}}" AGENT_RUNTIME_TWO_STACK_EVIDENCE="{{evidence}}" deploy/dev/run-two-stack-smoke.sh
