//go:build integration

package runtimeorchestration_test

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"log/slog"
	"os"
	"sync"
	"testing"
	"time"

	"github.com/0x63616c/agent-runtime/internal/runtimeorchestration"
	"github.com/0x63616c/agent-runtime/internal/temporalpayloadruntime"
	"github.com/0x63616c/agent-runtime/temporalpayload"
	historypb "go.temporal.io/api/history/v1"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/log"
	"go.temporal.io/sdk/testsuite"
	"go.temporal.io/sdk/worker"
	"google.golang.org/protobuf/proto"
)

func TestSessionWorkflowRunsThroughTheOwnedFactoryAgainstTemporal(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	server, err := testsuite.StartDevServer(ctx, testsuite.DevServerOptions{})
	if err != nil {
		t.Fatalf("start Temporal development server: %v", err)
	}
	defer func() { _ = server.Stop() }()
	blobs := &retainedReplayBlobStore{values: map[temporalpayload.BlobKey][]byte{}}
	codec, err := temporalpayload.NewCodec(blobs, temporalpayload.WithBlobPrefix("runtime-orchestration-integration"))
	if err != nil {
		t.Fatal(err)
	}
	factory, err := temporalpayloadruntime.NewFactory(codec)
	if err != nil {
		t.Fatal(err)
	}
	owned, err := factory.NewClient(ctx, client.Options{HostPort: server.FrontendHostPort()})
	if err != nil {
		t.Fatal(err)
	}
	defer owned.Close()
	workerRuntime, err := factory.NewWorker(owned, "runtime-orchestration-integration", worker.Options{})
	if err != nil {
		t.Fatal(err)
	}
	dispatcher := &integrationDispatcher{}
	activities, err := runtimeorchestration.NewActivities(dispatcher)
	if err != nil {
		t.Fatal(err)
	}
	if err := runtimeorchestration.Register(workerRuntime, activities); err != nil {
		t.Fatal(err)
	}
	if err := workerRuntime.Start(); err != nil {
		t.Fatal(err)
	}
	defer workerRuntime.Stop()
	run, err := owned.ExecuteWorkflow(ctx, client.StartWorkflowOptions{ID: "session-orchestration-integration", TaskQueue: "runtime-orchestration-integration"}, runtimeorchestration.SessionWorkflow, runtimeorchestration.WorkflowInput{SessionID: "sess_1234567890ABCDEF", ContinueAfter: 100})
	if err != nil {
		t.Fatalf("start Session workflow: %v", err)
	}
	commands := []runtimeorchestration.Command{
		{Tenant: "tenant-a", OutboxID: "outbox-input", SessionID: "sess_1234567890ABCDEF", Kind: runtimeorchestration.CommandInputAccepted, Sequence: 1},
		{Tenant: "tenant-a", OutboxID: "outbox-approval", SessionID: "sess_1234567890ABCDEF", Kind: runtimeorchestration.CommandApprovalResolved, Sequence: 2},
		{Tenant: "tenant-a", OutboxID: "outbox-sandbox", SessionID: "sess_1234567890ABCDEF", Kind: runtimeorchestration.CommandSandboxOperationFinalized, Sequence: 3},
		{Tenant: "tenant-a", OutboxID: "outbox-complete", SessionID: "sess_1234567890ABCDEF", Kind: runtimeorchestration.CommandSessionCompleted, Sequence: 4},
	}
	for _, command := range commands {
		if err := owned.SignalWorkflow(ctx, "session-orchestration-integration", run.GetRunID(), runtimeorchestration.SessionCommandSignal, command); err != nil {
			t.Fatalf("signal durable command %s: %v", command.Kind, err)
		}
		if !dispatcher.wait(ctx, command) {
			t.Fatalf("state-backed activity did not receive durable command %#v", command)
		}
	}
	if err := run.Get(ctx, nil); err != nil {
		t.Fatalf("complete durable lifecycle workflow: %v", err)
	}
	history, err := owned.WorkflowHistory(ctx, "session-orchestration-integration", run.GetRunID())
	if err != nil || len(history.Events) == 0 {
		t.Fatalf("retain actual Temporal history = %#v, %v", history, err)
	}
	replayer, err := factory.NewWorkflowReplayer()
	if err != nil {
		t.Fatal(err)
	}
	replayer.RegisterWorkflow(runtimeorchestration.SessionWorkflow)
	if err := replayer.ReplayWorkflowHistory(log.NewStructuredLogger(slog.New(slog.NewTextHandler(io.Discard, nil))), history); err != nil {
		t.Fatalf("replay retained actual Temporal Session history: %v", err)
	}
}

// TestSessionWorkflowReplaysCheckedInHistoricLifecycle retains a real,
// completed v1 Session workflow history in the repository. It catches a
// replay-incompatible workflow edit without depending on a live service or a
// new history generated by the code under test.
func TestSessionWorkflowReplaysCheckedInHistoricLifecycle(t *testing.T) {
	encoded, err := os.ReadFile("testdata/session-workflow-v1-history.json")
	if err != nil {
		t.Fatalf("read retained Session replay corpus: %v", err)
	}
	var corpus retainedReplayCorpus
	if err := json.Unmarshal(encoded, &corpus); err != nil {
		t.Fatalf("decode retained Session replay corpus: %v", err)
	}
	wire, err := base64.StdEncoding.DecodeString(corpus.History)
	if err != nil {
		t.Fatalf("decode retained Session replay history wire: %v", err)
	}
	history := &historypb.History{}
	if err := proto.Unmarshal(wire, history); err != nil {
		t.Fatalf("decode retained Session replay history: %v", err)
	}
	blobs := &retainedReplayBlobStore{values: map[temporalpayload.BlobKey][]byte{}}
	for key, encoded := range corpus.Blobs {
		value, err := base64.StdEncoding.DecodeString(encoded)
		if err != nil {
			t.Fatalf("decode retained payload blob %q: %v", key, err)
		}
		blobs.values[temporalpayload.BlobKey(key)] = value
	}
	codec, err := temporalpayload.NewCodec(blobs, temporalpayload.WithBlobPrefix("runtime-orchestration-integration"))
	if err != nil {
		t.Fatal(err)
	}
	factory, err := temporalpayloadruntime.NewFactory(codec)
	if err != nil {
		t.Fatal(err)
	}
	replayer, err := factory.NewWorkflowReplayer()
	if err != nil {
		t.Fatal(err)
	}
	replayer.RegisterWorkflow(runtimeorchestration.SessionWorkflow)
	if err := replayer.ReplayWorkflowHistory(log.NewStructuredLogger(slog.New(slog.NewTextHandler(io.Discard, nil))), history); err != nil {
		t.Fatalf("replay checked-in historic Temporal Session history: %v", err)
	}
}

type retainedReplayCorpus struct {
	History string            `json:"history"`
	Blobs   map[string]string `json:"blobs"`
}

// retainedReplayBlobStore is a test-only compatibility corpus seam. Production
// worker composition always uses the dedicated S3 payload capability; it has
// no MemoryBlobStore fallback.
type retainedReplayBlobStore struct {
	values map[temporalpayload.BlobKey][]byte
}

func (store *retainedReplayBlobStore) Put(_ context.Context, key temporalpayload.BlobKey, value []byte) error {
	if current, found := store.values[key]; found && !bytes.Equal(current, value) {
		return temporalpayload.ErrBlobIntegrity
	}
	store.values[key] = bytes.Clone(value)
	return nil
}

func (store *retainedReplayBlobStore) Get(_ context.Context, key temporalpayload.BlobKey, maximum int) ([]byte, error) {
	value, found := store.values[key]
	if !found {
		return nil, temporalpayload.ErrBlobNotFound
	}
	if len(value) > maximum {
		return nil, temporalpayload.ErrBlobTooLarge
	}
	return bytes.Clone(value), nil
}

type integrationDispatcher struct {
	mu       sync.Mutex
	commands []runtimeorchestration.Command
	notify   chan struct{}
}

func (dispatcher *integrationDispatcher) Dispatch(_ context.Context, command runtimeorchestration.Command) error {
	dispatcher.mu.Lock()
	dispatcher.commands = append(dispatcher.commands, command)
	notify := dispatcher.notify
	dispatcher.notify = make(chan struct{})
	if notify != nil {
		close(notify)
	}
	dispatcher.mu.Unlock()
	return nil
}

func (dispatcher *integrationDispatcher) wait(ctx context.Context, want runtimeorchestration.Command) bool {
	for {
		dispatcher.mu.Lock()
		for _, command := range dispatcher.commands {
			if command == want {
				dispatcher.mu.Unlock()
				return true
			}
		}
		notify := dispatcher.notify
		if notify == nil {
			notify = make(chan struct{})
			dispatcher.notify = notify
		}
		dispatcher.mu.Unlock()
		select {
		case <-notify:
		case <-ctx.Done():
			return false
		}
	}
}
