#!/usr/bin/env bash
# Renders or explicitly runs one disposable privileged Firecracker KVM pod on
# an operator-owned Linux node. It is deliberately separate from the normal
# application Stack: its only host access is the reviewed direct KVM authority
# and it always deletes its own uniquely named namespace.
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage:
  direct-kvm-runner.sh render --run-id ID --image ghcr.io/0x63616c/agent-runtime-direct-runner@sha256:HEX --output /absolute/manifest.yaml
  direct-kvm-runner.sh execute --run-id ID --image ghcr.io/0x63616c/agent-runtime-direct-runner@sha256:HEX --kubeconfig /absolute/KUBECONFIG --context CONTEXT --evidence-file /absolute/EVIDENCE.json --execute-authorized-direct-kvm
  direct-kvm-runner.sh --self-test

render is offline. execute is the only mutating mode. It refuses to reuse a
namespace, creates one privileged Pod Security namespace containing a single
no-network pod, waits for its bounded smoke run, retains only redacted stdout
and the root-owned smoke report, then deletes and waits for deletion of that
exact namespace even when the smoke command fails.
EOF
  exit 2
}

fail() { echo "direct KVM runner failed: $*" >&2; exit 1; }
valid_run_id() { [[ "$1" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ && ${#1} -le 24 ]]; }
valid_context() { [[ "$1" =~ ^[A-Za-z0-9@._:-]{1,128}$ ]]; }
valid_image() { [[ "$1" =~ ^ghcr\.io/0x63616c/agent-runtime-direct-runner@sha256:[0-9a-f]{64}$ ]]; }
require_new_absolute() { [[ "$1" == /* && ! -e "$1" ]] || fail "$2 must be a new absolute path"; mkdir -p "$(dirname "$1")"; }
require_file() { [[ "$1" == /* && -f "$1" ]] || fail "$2 must be an existing absolute file"; }

identity() {
  local run_id="$1"
  valid_run_id "$run_id" || fail "run ID must be a lowercase DNS label of at most 24 characters"
  namespace="agent-runtime-direct-kvm-$run_id"
  pod="firecracker-direct-kvm"
  [[ ${#namespace} -le 63 ]] || fail "derived namespace is too long"
  vm_id="agent-runtime-direct-$run_id"
  report_path="/var/lib/agent-runtime/firecracker-evidence/home-server/${run_id}.json"
}

render() {
  local run_id="" image="" output=""
  while [[ $# -gt 0 ]]; do case "$1" in
    --run-id) run_id="$2"; shift 2;; --image) image="$2"; shift 2;; --output) output="$2"; shift 2;; *) usage;;
  esac; done
  [[ -n "$run_id" && -n "$image" && -n "$output" ]] || usage
  identity "$run_id"; valid_image "$image" || fail "image must be the pinned reviewed direct-runner repository digest"
  require_new_absolute "$output" "output"
  cat >"$output" <<EOF
# Generated by direct-kvm-runner.sh. Apply only through its execute command.
apiVersion: v1
kind: Namespace
metadata:
  name: $namespace
  labels:
    app.kubernetes.io/part-of: agent-runtime
    agent-runtime.dev/direct-kvm-run: "$run_id"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: $namespace
  name: default-deny
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: v1
kind: Pod
metadata:
  namespace: $namespace
  name: $pod
  labels:
    app.kubernetes.io/part-of: agent-runtime
    agent-runtime.dev/direct-kvm-run: "$run_id"
spec:
  automountServiceAccountToken: false
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  containers:
    - name: firecracker
      image: $image
      imagePullPolicy: Always
      command: ["/bin/sh", "-ec"]
      args:
        - >-
          /usr/local/bin/firecracker-direct-preflight
          -config /var/lib/agent-runtime/firecracker-direct/kvm-config.json
          -fixture-lock /var/lib/agent-runtime/firecracker-fixtures/home-server/fixtures.lock
          && exec /usr/local/bin/firecracker-smoke
          -execution-mode direct
          -direct-config /var/lib/agent-runtime/firecracker-direct/kvm-config.json
          -direct-fixture-source-map /var/lib/agent-runtime/firecracker-direct/fixture-source-map.json
          -fixture-lock /var/lib/agent-runtime/firecracker-fixtures/home-server/fixtures.lock
          -report $report_path
          -vm-id $vm_id
          -uid 1000 -gid 1000
          -cgroup-parent agent-runtime/firecracker-direct
          -stack-resource firecracker-direct-kvm
          -external-owner firecracker-direct-limits
          -timeout 2m
      securityContext:
        privileged: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: true
        capabilities: { drop: ["ALL"] }
      resources:
        requests: { cpu: "1000m", memory: "1024Mi" }
        limits: { cpu: "2000m", memory: "2048Mi" }
      volumeMounts:
        - { name: tmp, mountPath: /tmp }
        - { name: kvm, mountPath: /dev/kvm }
        - { name: direct-config, mountPath: /var/lib/agent-runtime/firecracker-direct/kvm-config.json, readOnly: true }
        - { name: fixture-map, mountPath: /var/lib/agent-runtime/firecracker-direct/fixture-source-map.json, readOnly: true }
        - { name: fixtures, mountPath: /var/lib/agent-runtime/firecracker-fixtures/home-server, readOnly: true }
        - { name: evidence, mountPath: /var/lib/agent-runtime/firecracker-evidence/home-server }
        - { name: jailer, mountPath: /srv/agent-runtime/jailer }
        - { name: cgroup, mountPath: /sys/fs/cgroup/agent-runtime/firecracker-direct }
  volumes:
    - name: tmp
      emptyDir: { sizeLimit: 2Gi }
    - name: kvm
      hostPath: { path: /dev/kvm, type: CharDevice }
    - name: direct-config
      hostPath: { path: /var/lib/agent-runtime/firecracker-direct/kvm-config.json, type: File }
    - name: fixture-map
      hostPath: { path: /var/lib/agent-runtime/firecracker-direct/fixture-source-map.json, type: File }
    - name: fixtures
      hostPath: { path: /var/lib/agent-runtime/firecracker-fixtures/home-server, type: Directory }
    - name: evidence
      hostPath: { path: /var/lib/agent-runtime/firecracker-evidence/home-server, type: Directory }
    - name: jailer
      hostPath: { path: /srv/agent-runtime/jailer, type: Directory }
    - name: cgroup
      hostPath: { path: /sys/fs/cgroup/agent-runtime/firecracker-direct, type: Directory }
EOF
}

execute() {
  local run_id="" image="" kubeconfig="" context_value="" evidence="" approved=false manifest=""
  while [[ $# -gt 0 ]]; do case "$1" in
    --run-id) run_id="$2"; shift 2;; --image) image="$2"; shift 2;; --kubeconfig) kubeconfig="$2"; shift 2;; --context) context_value="$2"; shift 2;; --evidence-file) evidence="$2"; shift 2;; --execute-authorized-direct-kvm) approved=true; shift;; *) usage;;
  esac; done
  [[ "$approved" == true && -n "$run_id" && -n "$image" && -n "$kubeconfig" && -n "$context_value" && -n "$evidence" ]] || usage
  identity "$run_id"; valid_image "$image" || fail "image must be the pinned reviewed direct-runner repository digest"; valid_context "$context_value" || fail "invalid Kubernetes context"
  require_file "$kubeconfig" "kubeconfig"; require_new_absolute "$evidence" "evidence file"
  command -v kubectl >/dev/null || fail "kubectl is required"; command -v jq >/dev/null || fail "jq is required"
  kubectl --kubeconfig "$kubeconfig" config get-contexts -o name | grep -Fx -- "$context_value" >/dev/null || fail "explicit context is unavailable"
  [[ -z "$(kubectl --kubeconfig "$kubeconfig" --context "$context_value" get "namespace/$namespace" --ignore-not-found -o name)" ]] || fail "namespace already exists; runner will not take it over"
  manifest="$(mktemp)"; trap 'rm -f -- "${manifest:-}"' EXIT
  render --run-id "$run_id" --image "$image" --output "$manifest"
  local cleanup=true result=0 phase logs
  trap 'if [[ "${cleanup:-false}" == true ]]; then kubectl --kubeconfig "$kubeconfig" --context "$context_value" delete "namespace/$namespace" --ignore-not-found --wait=false >/dev/null || true; kubectl --kubeconfig "$kubeconfig" --context "$context_value" wait --for=delete "namespace/$namespace" --timeout=180s >/dev/null 2>&1 || echo "direct KVM cleanup failed; delete namespace $namespace" >&2; fi; rm -f -- "${manifest:-}"' EXIT
  kubectl --kubeconfig "$kubeconfig" --context "$context_value" apply -f "$manifest" >/dev/null
  if ! kubectl --kubeconfig "$kubeconfig" --context "$context_value" wait --for=jsonpath='{.status.phase}'=Succeeded "pod/$pod" --namespace "$namespace" --timeout=180s >/dev/null; then result=1; fi
  phase="$(kubectl --kubeconfig "$kubeconfig" --context "$context_value" get "pod/$pod" --namespace "$namespace" -o jsonpath='{.status.phase}' 2>/dev/null || true)"
  logs="$(kubectl --kubeconfig "$kubeconfig" --context "$context_value" logs "pod/$pod" --namespace "$namespace" --timestamps 2>&1 || true)"
  jq -n --arg namespace "$namespace" --arg pod "$pod" --arg context "$context_value" --arg image "$image" --arg report "$report_path" --arg phase "$phase" --arg logs "$logs" --argjson succeeded "$([[ "$result" == 0 ]] && echo true || echo false)" '{version:1,kind:"agent-runtime.direct-kvm-run/v1",namespace:$namespace,pod:$pod,context:$context,image:$image,host_report:$report,pod_phase:$phase,succeeded:$succeeded,pod_logs:$logs,cleanup:"namespace deletion follows this record"}' >"$evidence"
  kubectl --kubeconfig "$kubeconfig" --context "$context_value" delete "namespace/$namespace" --wait=false >/dev/null
  kubectl --kubeconfig "$kubeconfig" --context "$context_value" wait --for=delete "namespace/$namespace" --timeout=180s >/dev/null
  cleanup=false
  [[ "$result" == 0 ]] || fail "Firecracker pod did not reach Succeeded; redacted logs are in $evidence"
  echo "direct KVM smoke completed; evidence: $evidence"
}

self_test() {
  local tmp manifest
  tmp="$(mktemp -d)"; trap 'rm -rf -- "${tmp:-}"' EXIT
  manifest="$tmp/runner.yaml"
  render --run-id smoke-test --image "ghcr.io/0x63616c/agent-runtime-direct-runner@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" --output "$manifest"
  grep -Fqx '    pod-security.kubernetes.io/enforce: privileged' "$manifest"
  grep -Fqx '  policyTypes: [Ingress, Egress]' "$manifest"
  grep -Fqx '  automountServiceAccountToken: false' "$manifest"
  grep -Fqx '      imagePullPolicy: Always' "$manifest"
  grep -Fqx '        - { name: tmp, mountPath: /tmp }' "$manifest"
  grep -Fqx '      emptyDir: { sizeLimit: 2Gi }' "$manifest"
  grep -Fqx '      hostPath: { path: /dev/kvm, type: CharDevice }' "$manifest"
  grep -Fqx '      hostPath: { path: /var/lib/agent-runtime/firecracker-direct/kvm-config.json, type: File }' "$manifest"
  grep -Fqx '          -report /var/lib/agent-runtime/firecracker-evidence/home-server/smoke-test.json' "$manifest"
  if "$0" render --run-id upperCase --image "ghcr.io/0x63616c/agent-runtime-direct-runner@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" --output "$tmp/bad" >/dev/null 2>&1; then fail "accepted invalid run ID"; fi
  if "$0" render --run-id smoke-test --image "example.invalid/unpinned:latest" --output "$tmp/bad" >/dev/null 2>&1; then fail "accepted unreviewed image"; fi
  if "$0" execute --run-id smoke-test --image "ghcr.io/0x63616c/agent-runtime-direct-runner@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" --kubeconfig /dev/null --context home-server --evidence-file "$tmp/evidence.json" >/dev/null 2>&1; then fail "execute accepted no explicit authorization flag"; fi
  echo "direct KVM runner renders one pinned-image, privileged, no-network disposable namespace and refuses unpinned inputs"
}

case "${1:-}" in
  render) shift; render "$@";;
  execute) shift; execute "$@";;
  --self-test) self_test;;
  *) usage;;
esac
