// Code generated from api/openapi/openapi.yaml; DO NOT EDIT.

package runtimeapi

const (
	openAPIContractSHA256             = "c0771410aefe149ab6bad2dc98d025883e3b31b55170d91cb408055f5c6945e0"
	openAPIMethodCancelTurn           = "POST"
	openAPIPathCancelTurn             = "/v1/sessions/{session_id}/turns/{turn_id}/cancel"
	openAPIMethodCloseSession         = "POST"
	openAPIPathCloseSession           = "/v1/sessions/{session_id}/close"
	openAPIMethodCreateAgent          = "POST"
	openAPIPathCreateAgent            = "/v1/admin/agents"
	openAPIMethodCreatePolicy         = "POST"
	openAPIPathCreatePolicy           = "/v1/admin/policies"
	openAPIMethodCreateSession        = "POST"
	openAPIPathCreateSession          = "/v1/sessions"
	openAPIMethodDecideApproval       = "POST"
	openAPIPathDecideApproval         = "/v1/approvals/{approval_id}/decide"
	openAPIMethodGetAgentRevision     = "GET"
	openAPIPathGetAgentRevision       = "/v1/admin/agents/{agent_id}/revisions/{revision_id}"
	openAPIMethodGetPolicy            = "GET"
	openAPIPathGetPolicy              = "/v1/admin/policies/{policy_name}/revisions/{revision}"
	openAPIMethodIdempotencyStatus    = "GET"
	openAPIPathIdempotencyStatus      = "/v1/idempotency"
	openAPIMethodInspectApproval      = "GET"
	openAPIPathInspectApproval        = "/v1/approvals/{approval_id}"
	openAPIMethodInspectSession       = "GET"
	openAPIPathInspectSession         = "/v1/sessions/{session_id}"
	openAPIMethodInspectToolCalls     = "GET"
	openAPIPathInspectToolCalls       = "/v1/sessions/{session_id}/turns/{turn_id}/tools"
	openAPIMethodInspectTurn          = "GET"
	openAPIPathInspectTurn            = "/v1/sessions/{session_id}/turns/{turn_id}"
	openAPIMethodListApprovals        = "GET"
	openAPIPathListApprovals          = "/v1/approvals"
	openAPIMethodListEvents           = "GET"
	openAPIPathListEvents             = "/v1/sessions/{session_id}/events"
	openAPIMethodListSessionArtifacts = "GET"
	openAPIPathListSessionArtifacts   = "/v1/sessions/{session_id}/artifacts"
	openAPIMethodReadArtifact         = "GET"
	openAPIPathReadArtifact           = "/v1/artifacts/{artifact_id}"
	openAPIMethodReviseAgent          = "POST"
	openAPIPathReviseAgent            = "/v1/admin/agents/{agent_id}/revisions"
	openAPIMethodRevisePolicy         = "POST"
	openAPIPathRevisePolicy           = "/v1/admin/policies/{policy_name}/revisions"
	openAPIMethodSendInput            = "POST"
	openAPIPathSendInput              = "/v1/sessions/{session_id}/inputs"
)
