// Code generated from api/openapi/openapi.yaml; DO NOT EDIT.

package runtimeapi

const (
	openAPIContractSHA256          = "a5aadb169074938e7ff23e4827f3146a92a98cb89ca7ab75f90b2c4ee83577ca"
	openAPIMethodCancelTurn        = "POST"
	openAPIPathCancelTurn          = "/v1/sessions/{session_id}/turns/{turn_id}/cancel"
	openAPIMethodCloseSession      = "POST"
	openAPIPathCloseSession        = "/v1/sessions/{session_id}/close"
	openAPIMethodCreateAgent       = "POST"
	openAPIPathCreateAgent         = "/v1/admin/agents"
	openAPIMethodCreateSession     = "POST"
	openAPIPathCreateSession       = "/v1/sessions"
	openAPIMethodDecideApproval    = "POST"
	openAPIPathDecideApproval      = "/v1/approvals/{approval_id}/decide"
	openAPIMethodGetAgentRevision  = "GET"
	openAPIPathGetAgentRevision    = "/v1/admin/agents/{agent_id}/revisions/{revision_id}"
	openAPIMethodIdempotencyStatus = "GET"
	openAPIPathIdempotencyStatus   = "/v1/idempotency"
	openAPIMethodInspectApproval   = "GET"
	openAPIPathInspectApproval     = "/v1/approvals/{approval_id}"
	openAPIMethodInspectSession    = "GET"
	openAPIPathInspectSession      = "/v1/sessions/{session_id}"
	openAPIMethodInspectTurn       = "GET"
	openAPIPathInspectTurn         = "/v1/sessions/{session_id}/turns/{turn_id}"
	openAPIMethodListEvents        = "GET"
	openAPIPathListEvents          = "/v1/sessions/{session_id}/events"
	openAPIMethodReadArtifact      = "GET"
	openAPIPathReadArtifact        = "/v1/artifacts/{artifact_id}"
	openAPIMethodReviseAgent       = "POST"
	openAPIPathReviseAgent         = "/v1/admin/agents/{agent_id}/revisions"
	openAPIMethodSendInput         = "POST"
	openAPIPathSendInput           = "/v1/sessions/{session_id}/inputs"
)
